services:
  py3-knmt:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "8002:8888"
    volumes:
      - ./py3/root_jupyter:/root/.jupyter
      - ../workspace:/workspace

    #GPUを使う場合の設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu